language: php

dist: trusty #
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: CODE_COVERAGE=1
    - php: 7.2
    - php: 7.3
      dist: bionic # for proper node-less version
      env: BROWSER_TESTS=1
      addons:
        chrome: stable
        apt:
          packages:
            - node-less
    - php: 7.4

cache:
  directories:
    - $HOME/.composer

install:
  - .ci/install.sh

script:
  - .ci/run.sh

notifications:
  email: false
