name: "Send comment to stale PRs"
on:
  schedule:
    # Run everyday at midnight
    - cron: "0 0 * * *"

jobs:
  review-reminder:
    permissions:
      pull-requests: write
    if: github.repository == 'roundcube/roundcubemail'
    runs-on: ubuntu-latest
    steps:
      - uses: sojusan/github-action-reminder@v1
        with:
          reminder_message: "ğŸ›ï¸ This PR has had no activity in two weeks."
          # Remind after two weeks of inactivity
          inactivity_deadline_hours: 336
          default_users_to_notify: |
            @pabzm
            @alecpl
