name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        php: ["7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]

    name: PHP ${{ matrix.php }}/Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, fileinfo, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, ldap, intl, pspell, enchant
          tools: composer:v2
          coverage: none

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Aspell/Hunspell
        run: sudo apt-get -y install aspell aspell-en aspell-de hunspell-en-us

      - name: Setup composer
        run: |
            cp composer.json-dist composer.json
            composer require "kolab/net_ldap3:~1.1.4" --no-update

      - name: Fix PHPUnit for PHP 8.2
        run: composer config platform.php 8.1
        if: matrix.php >= 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Roundcube configuration
        run: cp .github/config-test.inc.php config/config-test.inc.php

      - name: Execute tests
        run: vendor/bin/phpunit -c tests/phpunit.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: logs/errors.log
